server:
  port: 9091



######################
mysql:
  user: root
  password: qscdew
  url: 127.0.0.1
  port: 3306
  dbname: fisco_bcos

#######################
redis:
  url: 127.0.0.1
  port: 6379
  db: 0


########################
mail:
  from: 514016929@qq.com

########################

zap:
  level: info
  format: console
  prefix: '[blockchain_platform]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
