// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add/role": {
            "post": {
                "tags": [
                    "管理员操作"
                ],
                "summary": "添加用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色id",
                        "name": "role_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "角色名称",
                        "name": "role_name",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/blockchain/contract/deploy": {
            "post": {
                "tags": [
                    "链上操作"
                ],
                "summary": "部署智能合约",
                "responses": {}
            }
        },
        "/blockchain/contract/edittx": {
            "post": {
                "tags": [
                    "链上操作"
                ],
                "summary": "编辑交易",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户私钥",
                        "name": "privateKey",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "交易地址",
                        "name": "txHash",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "编辑后的数据",
                        "name": "data",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/blockchain/contract/singletx": {
            "post": {
                "tags": [
                    "链上操作"
                ],
                "summary": "进行单笔交易",
                "parameters": [
                    {
                        "type": "string",
                        "description": "交易发送方",
                        "name": "from",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "交易接收方",
                        "name": "to",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "交易金额",
                        "name": "money",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/blockchain/contract/tracetx": {
            "post": {
                "tags": [
                    "监管者操作"
                ],
                "summary": "追溯交易",
                "parameters": [
                    {
                        "type": "string",
                        "description": "监管者私钥",
                        "name": "privateKey",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "交易地址",
                        "name": "txHash",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/blockchain/height": {
            "get": {
                "tags": [
                    "链上操作"
                ],
                "summary": "获取区块链高度",
                "responses": {}
            }
        },
        "/data/delete": {
            "post": {
                "tags": [
                    "数据提供用户操作"
                ],
                "summary": "数据提供用户删除数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "数据名称",
                        "name": "data_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "数据内容",
                        "name": "data_content",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/data/jugde": {
            "post": {
                "tags": [
                    "审计用户操作"
                ],
                "summary": "审计数据同步至主平台",
                "parameters": [
                    {
                        "type": "string",
                        "description": "数据ID",
                        "name": "data_id",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "该数据是否合法",
                        "name": "agree",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/data/provide": {
            "post": {
                "tags": [
                    "数据提供用户操作"
                ],
                "summary": "数据提供用户提供数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "数据名称",
                        "name": "data_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "数据内容",
                        "name": "data_content",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/data/thumbdown": {
            "post": {
                "tags": [
                    "数据浏览用户操作"
                ],
                "summary": "数据浏览用户点灭数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "数据名称",
                        "name": "data_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "数据内容",
                        "name": "data_content",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/data/thumbup": {
            "post": {
                "tags": [
                    "数据浏览用户操作"
                ],
                "summary": "数据浏览用户点赞热点数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "数据名称",
                        "name": "data_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "数据内容",
                        "name": "data_content",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/login": {
            "post": {
                "tags": [
                    "登录"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "账号",
                        "name": "username",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/register": {
            "post": {
                "tags": [
                    "常规用户操作"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "账号",
                        "name": "username",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "角色id",
                        "name": "role_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "mail",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/show/hot": {
            "get": {
                "tags": [
                    "数据浏览用户操作"
                ],
                "summary": "数据浏览用户查看热点数据",
                "responses": {}
            }
        },
        "/system/aggregate": {
            "post": {
                "tags": [
                    "系统操作"
                ],
                "summary": "系统聚合数据",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "是否开启聚合",
                        "name": "start",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/verify/email": {
            "post": {
                "tags": [
                    "智能合约用户操作"
                ],
                "summary": "智能合约用户确认邮件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "验证邮件",
                        "name": "verify_email",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/verify/user": {
            "post": {
                "tags": [
                    "管理员操作"
                ],
                "summary": "处理用户账号申请",
                "parameters": [
                    {
                        "type": "string",
                        "description": "申请id",
                        "name": "offer_id",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "是否同意创建",
                        "name": "ok",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "localhost:9091",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "区块链数据可修改实验平台",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
