basePath: /
host: localhost:9091
info:
  contact: {}
  title: 面向电子合同的可修正区块链系统
paths:
  /add/role:
    post:
      parameters:
      - description: 角色id
        in: formData
        name: role_id
        type: string
      - description: 角色名称
        in: formData
        name: role_name
        type: string
      responses: {}
      summary: 添加用户
      tags:
      - 管理员操作
  /amend/calculate:
    post:
      parameters:
      - description: 数据ID
        in: formData
        name: data_id
        type: string
      - description: 该数据是否合法
        in: formData
        name: agree
        type: boolean
      responses: {}
      summary: 计算信誉值
      tags:
      - 电子合同通信与修正模块
  /amend/contract/edittx:
    post:
      parameters:
      - description: 用户私钥
        in: formData
        name: privateKey
        type: string
      - description: 交易地址
        in: formData
        name: txHash
        type: string
      - description: 编辑后的数据
        in: formData
        name: data
        type: string
      responses: {}
      summary: 请求修正电子合同
      tags:
      - 电子合同通信与修正模块
  /amend/contract/singletx:
    post:
      parameters:
      - description: 交易发送方
        in: formData
        name: from
        type: string
      - description: 交易接收方
        in: formData
        name: to
        type: string
      - description: 交易金额
        in: formData
        name: money
        type: string
      responses: {}
      summary: 上传电子合同
      tags:
      - 电子合同通信与修正模块
  /amend/contract/tracetx:
    post:
      parameters:
      - description: 监管者私钥
        in: formData
        name: privateKey
        type: string
      - description: 交易地址
        in: formData
        name: txHash
        type: string
      responses: {}
      summary: 追溯修正操作
      tags:
      - 电子合同通信与修正模块
  /amend/eliminate:
    post:
      parameters:
      - description: 数据ID
        in: formData
        name: data_id
        type: string
      - description: 该数据是否合法
        in: formData
        name: agree
        type: boolean
      responses: {}
      summary: 淘汰低信誉用户
      tags:
      - 电子合同通信与修正模块
  /blockchain/contract/deploy:
    post:
      responses: {}
      summary: 部署智能合约
      tags:
      - 用户操作
  /blockchain/height:
    get:
      responses: {}
      summary: 获取区块链高度
      tags:
      - 管理员操作
  /login:
    post:
      parameters:
      - description: 账号
        in: formData
        name: username
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      responses: {}
      summary: 登录
      tags:
      - 用户操作
  /privacy/aggregate:
    post:
      parameters:
      - description: 是否开启聚合
        in: formData
        name: start
        type: boolean
      responses: {}
      summary: 聚合密钥
      tags:
      - 隐私保护模块
  /privacy/groupcreate:
    post:
      parameters:
      - description: 用户签名
        in: formData
        name: signature
        type: string
      responses: {}
      summary: 群创建
      tags:
      - 隐私保护模块
  /privacy/groupjoin:
    post:
      parameters:
      - description: 用户签名
        in: formData
        name: signature
        type: string
      responses: {}
      summary: 群加入
      tags:
      - 隐私保护模块
  /privacy/open:
    post:
      parameters:
      - description: 用户签名
        in: formData
        name: signature
        type: string
      responses: {}
      summary: 群签名打开
      tags:
      - 隐私保护模块
  /privacy/sign:
    post:
      parameters:
      - description: 用户签名
        in: formData
        name: signature
        type: string
      responses: {}
      summary: 电子合同签名
      tags:
      - 隐私保护模块
  /privacy/verify:
    post:
      parameters:
      - description: 用户签名
        in: formData
        name: signature
        type: string
      responses: {}
      summary: 群签名验证
      tags:
      - 隐私保护模块
  /register:
    post:
      parameters:
      - description: 账号
        in: formData
        name: username
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      - description: 角色id
        in: formData
        name: role_id
        type: string
      - description: 邮箱
        in: formData
        name: mail
        type: string
      responses: {}
      summary: 用户注册
      tags:
      - 用户操作
  /test/amend:
    post:
      responses: {}
      summary: 可修正
      tags:
      - 实验
  /test/amendattack:
    post:
      responses: {}
      summary: 可修正作恶节点
      tags:
      - 实验
  /test/privacy:
    post:
      responses: {}
      summary: 群签名
      tags:
      - 实验
  /test/privacydoor:
    post:
      responses: {}
      summary: 不同实验群签名
      tags:
      - 实验
  /verify/smartcontract:
    post:
      parameters:
      - description: 验证邮件
        in: formData
        name: verify_email
        type: string
      responses: {}
      summary: 确认智能合约
      tags:
      - 管理员操作
  /verify/user:
    post:
      parameters:
      - description: 申请id
        in: formData
        name: offer_id
        type: string
      - description: 是否同意创建
        in: formData
        name: ok
        type: boolean
      responses: {}
      summary: 处理用户账号申请
      tags:
      - 管理员操作
swagger: "2.0"
